Added instructions for Plasma >= 5.25
heckelson/i3-and-kde-plasma pull request #29
Opened 2022-06-17 09:51 UTC by jonah-chen

Updated the README by describing the fix in https://bugs.kde.org/show_bug.cgi?id=439481 (comment 7) into more understandable instructions.

Tested on my system running Arch Linux (5.18.3) with X11, Plasma 5.25.0, KDE Frameworks 5.95.0, and Qt 5.15.4.

2022-06-17 22:57 UTC, softmoth requested changes
Request changes to clarify that root privileges are not required.

2022-06-17 22:57 UTC, softmoth commented on README.md
> +Create a new service file called plasma-i3.service in `/usr/lib/systemd/user` directory as su.
This file can be created without root privileges in `$HOME/.config/systemd/user/plasma-i3.service` as well.

2022-06-17 22:57 UTC, softmoth commented on README.md
> +If you are using Plasma >= 5.25, you need to create a new service to run i3 the login to the Plasma(X11) session. If you are using Plasma < 5.25, you need to create a new XSession and login to that.
It looks like some text was garbled during editing. Maybe something like "to run i3 instead of kwin upon login the".

2022-06-17 23:03 UTC, softmoth commented on README.md
> +```sudo systemctl mask plasma-kwin_x11.target```
This should be done without root privileges:

```bash
systemctl mask plasma-kwin_x11.target --user
```

2022-06-18 01:12 UTC, jonah-chen commented
> Request changes to clarify that root privileges are not required.

Thank you for your suggestion. I will test them on my system.

2022-06-18 05:42 UTC, jonah-chen commented
I have applied your changes. Should be ready now :)

2022-06-18 11:00 UTC, merged

2022-06-18 11:00 UTC, heckelson commented
lgtm

thank you for the contribution :)

2022-06-18 18:09 UTC, softmoth commented
Thanks for this, it's very helpful!